name: "Setup Python"
description: "Install and setup python"
inputs:
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Ensure latest pip
      run: python -m pip install --upgrade pip
      shell: sh
