name: "Setup Hatch"
description: "Install and setup hatch to build"
inputs:
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install hatch
      run: pip install hatch
      shell: sh

    - name: "Creating test.${{ inputs.python-version }}"
      run: hatch env create "test.py${{ python-version }}"
      shell: sh
      with:
        python-version: ${{ inputs.python-version }}
